fix: updating to main postcss
salesforce/kagekiri pull request #18
Opened 2020-09-13 16:26 UTC by tedconn

This PR is more of a question - what was the original issue with the built-in node deprecate? Is it that it's not resolvable in the browser?

All the karma tests pass for me with this PR. Also I upgraded rollup-plugin-terser due to a critical npm vulnerability.

2020-09-14 18:25 UTC, nolanlawson requested changes
The issue with the built-in deprecate is that it vastly bloated the bundle size. Unfortunately the PR fixing this has still not been merged: https://github.com/postcss/postcss-selector-parser/pull/210

This PR increases the size of `dist/kagekiri.iife.min.js` from 53.8kB to 69.7kB so yeah, I would prefer not to merge this for now.  If we can solve the bloat issue, then I'd be happy to switch to mainline `postcss-selector-parser`.

2020-09-15 11:43 UTC, tedconn commented
They've merged the PR but we'll have to wait for it to be released, then I'll update the version and this PR.

2020-09-15 16:11 UTC, nolanlawson commented
Oh sweet! Just saw that. Yeah, let's wait for a patch release then.

2020-09-21 16:28 UTC, nolanlawson commented
They've done a new release, but this PR has merge conflicts. Closing in favor of https://github.com/salesforce/kagekiri/pull/35

2020-09-21 16:28 UTC, closed without merging